import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Sovereign OS",
    short_name: "Sovereign",
    description: "Understand who you are — and why your relationships work the way they do.",
    start_url: "/chat",
    display: "standalone",
    background_color: "#0d0d0d",
    theme_color: "#0d0d0d",
    icons: [
      {
        src: "/brand/icon.png?v=2",
        sizes: "64x64",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/brand/apple-icon.png?v=2",
        sizes: "180x180",
        type: "image/png",
        purpose: "any",
      },
      // Install surfaces pick the icon nearest the slot they need and will
      // upscale anything smaller, so the two canonical sizes ship exactly
      // once each. All four are generated by scripts/build-brand-assets.mjs
      // from the same Ace-of-Cups mark.
      {
        src: "/brand/pwa-192x192.png?v=1",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/brand/pwa-512x512.png?v=1",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      // Maskable companions for launchers that crop to a circle or squircle:
      // the graphite plate fills the whole canvas and the mark sits inside the
      // safe zone, so a home-screen install never clips the emblem.
      {
        src: "/brand/maskable-192x192.png?v=1",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/brand/maskable-512x512.png?v=1",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}