import { Nav } from "@/components/nav";

export default function TermsPage() {
  return (
    <>
      <Nav />
      <main className="mx-auto max-w-3xl px-6 py-12">
        <h1 className="mb-2 text-3xl font-bold">Terms of Service</h1>
        <p className="mb-8 text-sm text-muted-foreground">Last updated: September 11, 2026</p>
        <div className="space-y-6 text-sm leading-relaxed text-muted-foreground">
          <section><h2 className="mb-2 text-lg font-semibold text-foreground">1. Acceptance of Terms</h2><p>By creating an account or using Sovereign OS ("the Service"), you agree to these Terms of Service. If you do not agree, please do not use the Service.</p></section>
          <section><h2 className="mb-2 text-lg font-semibold text-foreground">2. The Service</h2><p>Sovereign OS provides AI-assisted pattern analysis based on your baseline — computed from your date, time, and place of birth using NASA/JPL planetary data. The Service synthesizes emotional expression and offers pattern interruptions for personal reflection.</p></section>
          <section><h2 className="mb-2 text-lg font-semibold text-foreground">3. Accounts</h2><p>You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must provide accurate information when creating an account.</p></section>
          <section><h2 className="mb-2 text-lg font-semibold text-foreground">4. Subscriptions &amp; Billing</h2><p>The Service offers a free tier and a paid subscription ("Sovereign+"). Paid subscriptions are billed monthly or annually through Stripe. You may cancel at any time; access continues through the end of the paid period.</p></section>
          <section><h2 className="mb-2 text-lg font-semibold text-foreground">5. Acceptable Use</h2><p>You agree not to misuse the Service, including attempting to access other users&apos; accounts or data, probing or scanning for vulnerabilities, or using the Service for any unlawful purpose.</p></section>
          <section><h2 className="mb-2 text-lg font-semibold text-foreground">6. Disclaimer of Warranties</h2><p>The Service is provided "as is" without warranties of any kind. Content generated by the AI is for informational and reflective purposes only and is not professional advice.</p></section>
          <section><h2 className="mb-2 text-lg font-semibold text-foreground">7. Limitation of Liability</h2><p>To the maximum extent permitted by law, Sovereign OS shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service.</p></section>
          <section><h2 className="mb-2 text-lg font-semibold text-foreground">8. Changes to Terms</h2><p>We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the revised Terms.</p></section>
          <section><h2 className="mb-2 text-lg font-semibold text-foreground">9. Contact</h2><p>Questions about these Terms can be directed to <a href="mailto:info@sovereign.os" className="underline hover:text-foreground">info@sovereign.os</a>.</p></section>
        </div>
      </main>
    </>
  );
}
